version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.7.2
    container_name: prometheus
    volumes:
      - /etc/localtime:/etc/localtime
      - ./prom/prometheus:/etc/prometheus
      - ./prom/data:/prometheus
      - /etc/hosts:/etc/hosts
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - alert

  grafana:
    image: grafana/grafana:6.0.0
    container_name: grafana
    depends_on:
      - prometheus
    links:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/conf:/usr/share/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - /etc/localtime:/etc/localtime
    restart: always

  alert:
    image: prom/alertmanager
    restart: always
    container_name: alert
    volumes:
    - /etc/localtime:/etc/localtime
    - ./alert/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
    - 9093:9093
    links:
    - dingtalk

  dingtalk:
    image: timonwong/prometheus-webhook-dingtalk
    restart: always
    container_name: dingtalk
    volumes:
    - /etc/localtime:/etc/localtime
    command: '--ding.profile="dingtalk=https://oapi.dingtalk.com/robot/send?access_t40f64f130d61055a02c3bf86d0809ba7c2dc9c17e018643009986e89fe974"'
