version: '2'
services:
    alpine:
        image: alpine:latest
        hostname: alpine
        command: tail -f /etc/passwd
        logging:
            driver: syslog
            options:
                syslog-address: "tcp://192.168.4.32:50000"
                tag: alpine
