version: "3"
services:
  jenkins:
    container_name: jenkins
    hostname: jenkins
    image: jenkins-rsync:v1
    restart: always
    user: jenkins
    environment:
    - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
    volumes:
    - $PWD/jenkins_home:/var/jenkins_home
    - /etc/localtime:/etc/localtime
    extra_hosts:
    - dev:172.16.0.2
# 执行以下命令启动容器
# docker build -t jenkins-rsync:v1
# mkdir jenkins_home && chown 1000:1000 jenkins_home && docker-comose up -d
# cat jenkins_home/secrets/initialAdminPassword 获取jenkins安装密码
