on: '2'
services:
  es:
    container_name: es
    hostname: es
    restart: always
    image: elasticsearch:6.4.2
    volumes:
      - $PWD/elasticsearch:/usr/share/elasticsearch
      - /etc/localtime:/etc/localtime
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200
  logstash:
    container_name: logstash
    hostname: logstash
    restart: always
    image: logstash:6.4.2
    volumes:
      - $PWD/logstash:/usr/share/logstash
      - /etc/localtime:/etc/localtime
    ports:
      - 15044:5044
    links:
      - es
    depends_on:
      - es
    command: logstash --path.settings /usr/share/logstash/config
  kibana:
    container_name: kibana
    hostname: kibana
    restart: always
    image: kibana:6.4.2
    volumes:
      - $PWD/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - /etc/localtime:/etc/localtime
    ports:
      - 5600:5601
    links:
      - es
    depends_on:
      - es
