version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: Bo55man69
    volumes:
    - ./mysql:/var/lib/mysql
    - ./conf:/etc/mysql
    ports:
    - 3306:3306/tcp
